java: utils: downloader: Pass empty string when response is null
* Should fix something like this:
    Build version: 4.0
    Build date: 1981-01-01 01:01:02
    Current date: 2022-09-09 16:51:09
    Device: Xiaomi M2010J19SG
    OS version: Android 11 (SDK 30)

    Stack trace:
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to get length of null array
     at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(Unknown Source:11)
     at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(Unknown Source:179)
     at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(Unknown Source:2)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:236)
     at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: java.lang.NullPointerException: Attempt to get length of null array
     at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
     at m3.b.onFailure(Unknown Source:4)
     at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(Unknown Source:132)
     ... 4 more

    User actions:
    2022-09-09 16:50:09: BrowserActivity created
    2022-09-09 16:50:09: BrowserActivity resumed
    2022-09-09 16:50:10: MainActivity destroyed
    2022-09-09 16:50:11: BrowserActivity paused
    2022-09-09 16:50:11: SettingsActivity created
    2022-09-09 16:50:11: SettingsActivity resumed
    2022-09-09 16:50:16: SettingsActivity paused
    2022-09-09 16:50:16: BrowserActivity resumed
    2022-09-09 16:50:16: SettingsActivity destroyed

Signed-off-by: Ricky Cheung <rcheung844@gmail.com>
Change-Id: I46caf9d1be79f39189ec1581a0b660efe1435ae5