java: browser: Fix crash when creating app shortcut before page loaded
* This crash case is almost not possible to reproduce as
  homepage should load quite quickly with cache and a good
  internet connection.
* It could be performed by clearing cache and limiting network
  speed so that the homepage will load slower than normal,
  allowing the user to create an app shortcut in this time frame.
* Crash report:
Build version: 4.0
Build date: 1981-01-01 01:01:02
Current date: 2022-12-04 12:43:45
Device: Sony XQ-CT72
OS version: Android 13 (SDK 33)

Stack trace:
java.lang.IllegalArgumentException: Shortcut must have a non-empty label
 at w.a.a(Unknown Source:32)
 at r3.d.onClick(SourceFile:14)
 at android.view.View.performClick(View.java:7516)
 at android.view.View.performClickInternal(View.java:7490)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29349)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:346)
 at android.os.Looper.loop(Looper.java:475)
 at android.app.ActivityThread.main(ActivityThread.java:7954)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

User actions:
2022-12-04 12:43:22: BrowserActivity created
2022-12-04 12:43:22: BrowserActivity resumed
2022-12-04 12:43:22: MainActivity destroyed

Signed-off-by: Ricky Cheung <rcheung844@gmail.com>
Change-Id: Ie73b90adaa66bba4c3338eb05f5df22423f2aeec