ext: Check whether contentType is null before usage
Prevents the following warnings from showing:
An exception occured during performFiltering()!
java.lang.NullPointerException: getContentType(...) must not be null

Change-Id: I41400fa68d1e42f0d1e6fb6bebcde678b9705f9e
Signed-off-by: Ricky Cheung <rcheung844@gmail.com>