main: java: Add noReload
Used to fix a null object reference, like the following:

2021-07-04 17:18:13.441 16372-16372/tipz.browservio E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tipz.browservio, PID: 16372
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1000, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {tipz.browservio/tipz.browservio.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5199)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5240)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2168)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8145)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at tipz.browservio.MainActivity.lambda$initialize$3$MainActivity(MainActivity.java:193)
        at tipz.browservio.MainActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7515)
        at tipz.browservio.MainActivity.setDesktopMode(MainActivity.java:120)
        at tipz.browservio.MainActivity.deskModeSet(MainActivity.java:125)
        at tipz.browservio.MainActivity.initializeLogic(MainActivity.java:398)
        at tipz.browservio.MainActivity.onRequestPermissionsResult(MainActivity.java:110)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8769)
        at android.app.Activity.dispatchActivityResult(Activity.java:8613)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5240) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2168) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8145) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 

Signed-off-by: Ricky Cheung <rcheung844@gmail.com>